# =============================================================================
# pve-herc - Host Variables
# =============================================================================

# Legacy host uses johnny user
admin_user: johnny
