# =============================================================================
# syncthing-lxc - Package Configuration
# =============================================================================

# Extra packages for this host
packages_host_extra: []
