$ANSIBLE_VAULT;1.1;AES256
33663035613738336537366437356339383233396433623265633366663136643936376537376335
6363663862643061626634366135623631326236316333360a313936363031646233313865303231
36383861633162366638356531303536623565393239353366353534393862633538666530643134
3134633566326234640a643833333963383335393931373139663832643836396535303235613964
37643630383966373364613134376265616564316639396263323931363865643032343430313361
30643032313138333764316137643434653062383866376231633330306536363133323634313330
64323633646466306433653032383239383736393434333833323565363062383262333264323931
61666465636262373934316532383635303665313836353239623235396135396238383034393630
3537
