# =============================================================================
# LXC Containers - Specific Packages
# =============================================================================
# These packages are only for LXCs (not VMs)

packages_lxcs_extra: []
