# =============================================================================
# ts440 - Package Configuration
# =============================================================================

# Extra packages for this host
packages_host_extra:
  - zfsutils-linux
